#!/usr/bin/env bash
# Shared helpers of the lockfile harness. Sourced by prepare.sh and judge.sh.
H="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$H/portable.sh"
BBCBENCH_ROOT="$(cd "$H/../.." && pwd)"
CASES_ROOT="${CASES_ROOT:-$BBCBENCH_ROOT/cases}"
CACHE_ROOT="${BBCBENCH_CACHE:-$BBCBENCH_ROOT/.scratch/repo-cache}"
TEST_TIMEOUT="${TEST_TIMEOUT:-1200}"
INSTALL_TIMEOUT="${INSTALL_TIMEOUT:-1800}"
export NO_PROXY='*'

die() { echo "error: $*" >&2; exit 2; }
say() { echo "=== $*"; }

# Test-count extraction, shared with rebuild_harness.sh (its counts() reads the summary line of
# mocha, tape, ava, vitest, uvu, jest and pytest). counts_nonzero tells whether any test ran.
CFN="$(sed -n '/^counts() {/,/^}/p' "$H/rebuild_harness.sh")"
eval "$(printf '%s\n' "$CFN" | sed '1s/^counts()/counts_harness()/')"
counts_pytest() {
  sed -e 's/\x1b\[[0-9;]*m//g' -e 's/=//g' "$1" \
    | grep -aE 'in [0-9][0-9.:]*s *$' \
    | grep -aoE '[0-9]+ (passed|failed|errors?|skipped|xfailed|xpassed)([^A-Za-z]|$)' \
    | sed 's/[^A-Za-z0-9 ]*$//' | sort | tr '\n' ' '
}
counts() { printf '%s%s' "$(counts_harness "$1")" "$(counts_pytest "$1")"; }
counts_nonzero() { [ -n "$1" ] && printf '%s' "$1" | grep -qE '[1-9]'; }

# load_case <case_id>
# Reads cases/<case_id>/meta.json. Sets CASE CDIR PIN SLUG COMMIT LIB VOLD VNEW TESTCMD IMAGE ECO NEWMODE.
load_case() {
  CASE="$1"; CDIR="$CASES_ROOT/$CASE"; PIN="$CDIR/pinned"
  [ -f "$CDIR/meta.json" ] || die "unknown case: $CASE"
  eval "$(python3 - "$CDIR/meta.json" <<'PY'
import json, sys, shlex
m = json.load(open(sys.argv[1], encoding='utf-8'))
rt = m.get('runtime') or {}
def q(k, v): print('%s=%s' % (k, shlex.quote('' if v is None else str(v))))
q('HARNESS_KIND', m.get('harness')); q('SLUG', m.get('repo')); q('COMMIT', m.get('commit'))
q('LIB', m.get('lib')); q('VOLD', m.get('v_old')); q('VNEW', m.get('v_new'))
q('TESTCMD', m.get('test_cmd', 'npm test')); q('IMAGE', rt.get('image'))
q('NODEMAJOR', rt.get('node_major')); q('PYMINOR', rt.get('python_minor'))
PY
)"
  [ "$HARNESS_KIND" = lockfile ] || die "$CASE is an image case; use harness/image"
  [ -n "$SLUG" ] && [ -n "$COMMIT" ] && [ -n "$LIB" ] && [ -n "$VNEW" ] && [ -n "$IMAGE" ] || die "meta.json of $CASE is incomplete"
  if [ -n "$NODEMAJOR" ]; then ECO=npm; SRCNAME=src
    [ -f "$PIN/lock-OLD.json" ] || die "missing $PIN/lock-OLD.json"
    NEWMODE="$(cat "$PIN/new-mode.txt" 2>/dev/null || echo swap)"
  elif [ -n "$PYMINOR" ]; then ECO=pip; SRCNAME=repo; NEWMODE=piplock
    [ -f "$PIN/lock-NEW.txt" ] || die "missing $PIN/lock-NEW.txt"
  else die "runtime of $CASE declares neither node_major nor python_minor"; fi
}

ensure_image() { docker image inspect "$IMAGE" >/dev/null 2>&1 || docker pull "$IMAGE" >/dev/null 2>&1 || die "cannot pull $IMAGE"; }

# rt <net|nonet> <seconds, 0 = unlimited> <command>: run a command inside the runtime image.
# Needs WK and SRC. The project is mounted at /w (npm) or /work/repo (pip).
rt() {
  local net="$1" secs="$2"; shift 2
  local cmd="$*" rc
  local tmo=(); [ "$secs" != 0 ] && tmo=(timeout -k 20 "$secs")
  local netarg=(); [ "$net" = nonet ] && netarg=(--network none)
  if [ "$ECO" = npm ]; then
    "${tmo[@]}" docker run --rm "${netarg[@]}" -u "$(id -u):$(id -g)" \
      -v "$SRC":/w -v "$WK/rt-home":/rt-home -w /w \
      -e HOME=/rt-home -e npm_config_cache=/rt-home/.npm -e NO_PROXY='*' \
      "$IMAGE" bash -c "$cmd"
  else
    "${tmo[@]}" docker run --rm "${netarg[@]}" -u "$(id -u):$(id -g)" \
      -v "$WK":/work -w /work/repo \
      -e HOME=/work/.home -e TMPDIR=/work/.tmp -e CI=true -e PYTHONDONTWRITEBYTECODE=1 \
      -e PIP_CACHE_DIR=/work/.pipcache -e PIP_DISABLE_PIP_VERSION_CHECK=1 -e NO_PROXY='*' \
      "$IMAGE" bash -c "export PATH=/work/.venv/bin:\$PATH; $cmd"
  fi
  rc=$?; return $rc
}

# The test command wrapped for the workspace. Regenerated by judge.sh, so an edited copy is never trusted.
run_tests_script() {
  echo '#!/usr/bin/env bash'
  echo "# Runs the tests of $CASE inside its pinned runtime image. Exit code 0 means the tests pass."
  if [ "$ECO" = npm ]; then
    cat <<WRAP
exec docker run --rm --network none -u "\$(id -u):\$(id -g)" \\
  -v "$SRC":/w -v "$WK/rt-home":/rt-home -w /w \\
  -e HOME=/rt-home -e npm_config_cache=/rt-home/.npm -e NO_PROXY='*' \\
  "$IMAGE" bash -c $(printf '%q' "$TESTCMD")
WRAP
  else
    cat <<WRAP
exec docker run --rm --network none -u "\$(id -u):\$(id -g)" \\
  -v "$WK":/work -w /work/repo \\
  -e HOME=/work/.home -e TMPDIR=/work/.tmp -e CI=true -e PYTHONDONTWRITEBYTECODE=1 -e NO_PROXY='*' \\
  "$IMAGE" bash -c $(printf '%q' "export PATH=/work/.venv/bin:\$PATH; $TESTCMD")
WRAP
  fi
}
run_suite() { timeout -k 30 "$TEST_TIMEOUT" bash "$1" > "$2" 2>&1; }

# Content fingerprint of the installed dependency tree (every file hashed). Test-runner caches are skipped.
tree_fingerprint() {
  if [ "$ECO" = npm ]; then python3 "$H/treehash.py" "$SRC/node_modules" | grep -vE '/\.(vitest|cache)/'
  else python3 "$H/treehash.py" "$WK/.venv"; fi
}

lib_ver_npm() { python3 - "$SRC/node_modules/$LIB/package.json" <<'PY'
import json,sys
try: print(json.load(open(sys.argv[1],encoding='utf-8')).get('version',''))
except Exception: print('')
PY
}
