#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Content gate against leaking the answer into BBCFixer evidence (second layer, defence in depth).

The first layer is the source gate, guaranteed by construction by lockfile.sh,
slicing/upstream_diff.sh and diffexec/diffexec_lockfile.sh together: every step of evidence generation runs in a
container, and the only things mounted are the two release artifacts of the library, the mirror
of the library repository, a copy of the downstream workspace, the round 0 error log and the
output directory; **the case directory is never mounted**, so reference_fix.patch and meta.json are
physically unreadable. The source gate is stronger than any after-the-fact check because it
does not depend on how complete the check is. This file is the second layer; it catches the
situation where the source gate is later rewritten and bypassed.

The criterion bans **finished text that can only come from the case directory**:
  the added/deleted lines of reference_fix.patch, the prose fields of meta.json, the case name, the
  three-state logs and the audit records.
The library name and the name of the offending method are not banned: they are supposed to
appear in the library diff and in the measured divergence, and treating them as leaks would
cripple BBCFixer, which is as much a fabricated experiment as weakening a baseline.

One further criterion: **the raw diff must not appear in the evidence directory**. The hard
rule of library diff filtering (Section 3.2.2) is never to hand the whole raw diff to the
agent; when slicing is bypassed, the raw file sits in the evidence directory, so this gate
treats that as a failure on the same level as a leak.

Usage:
  gate.py <evidence dir> <case dir>      normal check, exit 0 on pass
  gate.py --selfcheck <case dir>         positive and negative self-check
"""
import json
import os
import re
import shutil
import sys
import tempfile

PROSE_FIELDS = ("behavioral_change", "downstream_effect", "reference_fix", "documented_in",
                "root_api", "root_symbols", "failing_tests")
MIN_LEN = 24
# List of the evidence files handed to the agent. Any addition or removal must be made here,
# so that a new evidence file cannot silently bypass this gate.
EVIDENCE_FILES = ("code-diff-slice.txt", "test-diff.txt", "behavior-diff.md",
                  "contract.md", "entry-symbols.txt", "evidence-guide.md",
                  "README.md")
# Raw diffs and run captures: they may only stay in the log directory of evidence generation
# and must never enter the evidence directory.
RAW_FORBIDDEN = ("source-diff.raw", "test-diff.raw", "behavior-diff.json",
                 "trace.jsonl", "test-output.txt")


def norm(s):
    return re.sub(r"\s+", " ", s).strip()


def patch_lines(case_dir):
    p = os.path.join(case_dir, "reference_fix.patch")
    out = set()
    if not os.path.isfile(p):
        return out
    for line in open(p, encoding="utf-8", errors="replace"):
        if line[:1] in ("+", "-") and not line.startswith(("+++", "---")):
            t = norm(line[1:])
            if len(t) >= MIN_LEN:
                out.add(t)
    return out


def prose_snippets(case_dir):
    p = os.path.join(case_dir, "meta.json")
    out = set()
    if not os.path.isfile(p):
        return out
    try:
        m = json.load(open(p, encoding="utf-8"))
    except (OSError, ValueError):
        return out

    def harvest(v):
        if isinstance(v, str):
            for piece in re.split(r"[。；;.\n]", v):
                t = norm(piece)
                if len(t) >= MIN_LEN:
                    out.add(t)
        elif isinstance(v, dict):
            for x in v.values():
                harvest(x)
        elif isinstance(v, list):
            for x in v:
                harvest(x)

    for f in PROSE_FIELDS:
        if f in m:
            harvest(m[f])
    return out


# The products of the measured channel (generated by re-running the downstream tests under
# differential execution) necessarily reproduce, independently, the observable phenomena quoted
# in the meta.json prose (error messages, downstream file paths, etc.), so such a match does not
# constitute "can only come from the case directory". The meta prose ban is therefore waived for
# these two files; the bans on reference_fix.patch lines and on the case name stay in force for all
# evidence files: a legitimate measured record reflects the pre-fix behaviour and cannot
# legitimately contain the fix text.
MEASURED_FILES = ("behavior-diff.md", "contract.md")


def check(ev_dir, case_dir):
    case = os.path.basename(case_dir.rstrip("/"))
    banned_patch = patch_lines(case_dir)
    banned_prose = prose_snippets(case_dir)
    problems = []
    scanned = 0
    for fn in EVIDENCE_FILES:
        p = os.path.join(ev_dir, fn)
        if not os.path.isfile(p):
            continue
        scanned += 1
        body = open(p, encoding="utf-8", errors="replace").read()
        nb = norm(body)
        if case in body:
            problems.append("%s contains the case name %s" % (fn, case))
        for t in banned_patch:
            if t in nb:
                problems.append("%s contains text that can only come from the case directory: %.60s…" % (fn, t))
        if fn not in MEASURED_FILES:
            for t in banned_prose:
                if t in nb:
                    problems.append("%s contains text that can only come from the case directory: %.60s…" % (fn, t))
    # An empty evidence directory must fail: a pass that "scanned 0 files and found no problem"
    # reads exactly like a real pass, which is the kind of silent wrong answer this project has
    # hit repeatedly. The criterion lives in check() rather than in main(); otherwise the
    # self-check never reaches it and the criterion is effectively unchecked.
    if scanned == 0:
        problems.append("no evidence file at all in the evidence directory (%s); nothing to check" % ev_dir)
    # The raw diff must never enter the evidence directory (hard rule of library diff filtering)
    for fn in RAW_FORBIDDEN:
        if os.path.isfile(os.path.join(ev_dir, fn)):
            problems.append("unsliced raw product %s in the evidence directory (hard rule: never hand the whole raw diff to the agent)" % fn)
    # Finished files of the case directory must not be copied wholesale into the evidence directory
    for root, _, fns in os.walk(case_dir):
        for f in fns:
            if f in ("reference_fix.patch", "meta.json", "log-mentions.txt") or f.startswith("STATE-"):
                if os.path.isfile(os.path.join(ev_dir, f)):
                    problems.append("case artifact %s in the evidence directory" % f)
    return problems, scanned, len(banned_patch) + len(banned_prose)


def selfcheck(case_dir):
    wrong = 0
    tmp = tempfile.mkdtemp(prefix="ourgate-")
    try:
        ok_dir = os.path.join(tmp, "ok")
        os.makedirs(ok_dir)
        meta = json.load(open(os.path.join(case_dir, "meta.json"), encoding="utf-8"))
        open(os.path.join(ok_dir, "code-diff-slice.txt"), "w", encoding="utf-8").write(
            "# lodash 3.10.1 -> 4.17.21 的上游源码差异切片\n-function max(a, b) {\n+function maxBy(a, b) {\n")
        # Measured products legitimately reproduce the phenomena quoted in the meta prose (the
        # waived area); the positive case must cover this directly
        open(os.path.join(ok_dir, "behavior-diff.md"), "w", encoding="utf-8").write(
            "# 实测行为差异报告\n★ `lodash.max`：旧环境返回 A，新环境返回 B\n"
            + str(meta.get("behavioral_change", "")) + "\n")
        p, _, nbanned = check(ok_dir, case_dir)
        if p:
            wrong += 1
            for x in p:
                print("       %s" % x)
        print("positive %-6s evidence with only the library diff slice and the measured diff should pass        problems=%d"
              % ("OK" if not p else "WRONG", len(p)))

        cases = []
        d1 = os.path.join(tmp, "bad1"); os.makedirs(d1)
        shutil.copy(os.path.join(ok_dir, "behavior-diff.md"), d1)
        gp = open(os.path.join(case_dir, "reference_fix.patch"), encoding="utf-8", errors="replace").read()
        open(os.path.join(d1, "code-diff-slice.txt"), "w", encoding="utf-8").write(
            "# 上游源码差异切片\n" + gp)
        cases.append(("reference_fix.patch spliced into the evidence", d1))

        d2 = os.path.join(tmp, "bad2"); os.makedirs(d2)
        open(os.path.join(d2, "code-diff-slice.txt"), "w", encoding="utf-8").write(
            "# 上游源码差异切片\n" + str(meta.get("behavioral_change", "")))
        cases.append(("behavioral_change of meta.json spliced into declared-channel evidence", d2))

        d3 = os.path.join(tmp, "bad3"); os.makedirs(d3)
        shutil.copy(os.path.join(ok_dir, "code-diff-slice.txt"), d3)
        shutil.copy(os.path.join(case_dir, "reference_fix.patch"), d3)
        cases.append(("reference_fix.patch copied whole into the evidence directory", d3))

        d4 = os.path.join(tmp, "bad4"); os.makedirs(d4)
        open(os.path.join(d4, "contract.md"), "w", encoding="utf-8").write(
            "# 升级行为契约\n见案例 %s 的记录\n" % os.path.basename(case_dir.rstrip("/")))
        cases.append(("case name appears in the evidence", d4))

        d5 = os.path.join(tmp, "bad5"); os.makedirs(d5)
        cases.append(("no evidence file at all in the evidence directory", d5))

        d6 = os.path.join(tmp, "bad6"); os.makedirs(d6)
        shutil.copy(os.path.join(ok_dir, "code-diff-slice.txt"), d6)
        open(os.path.join(d6, "source-diff.raw"), "w", encoding="utf-8").write("diff -ruN ...\n")
        cases.append(("unsliced raw diff sitting in the evidence directory", d6))

        d7 = os.path.join(tmp, "bad7"); os.makedirs(d7)
        shutil.copy(os.path.join(ok_dir, "code-diff-slice.txt"), d7)
        shutil.copy(os.path.join(case_dir, "meta.json"), d7)
        cases.append(("meta.json copied whole into the evidence directory", d7))

        for label, d in cases:
            p, _, _ = check(d, case_dir)
            r = "OK" if p else "WRONG"
            if not p:
                wrong += 1
            print("negative %-6s %-44s problems=%d" % (r, label, len(p)))

        print("%d banned text snippets in total (reference_fix.patch changed lines + long meta.json prose sentences)" % nbanned)
        print("negative cases a degraded always-pass implementation would pass: 0 / %d" % len(cases))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return wrong


def main():
    if sys.argv[1] == "--selfcheck":
        w = selfcheck(sys.argv[2].rstrip("/"))
        print("OUR_GATE_SELFCHECK_%s" % ("OK" if w == 0 else "FAIL"))
        sys.exit(0 if w == 0 else 1)
    ev, cd = sys.argv[1], sys.argv[2].rstrip("/")
    problems, scanned, nbanned = check(ev, cd)
    print("our_gate: scanned %d evidence files, %d banned text snippets" % (scanned, nbanned))
    for p in problems:
        print("  BAD  %s" % p)
    if problems:
        print("OUR_GATE_FAIL %d problems" % len(problems))
        sys.exit(1)
    print("OUR_GATE_OK")


if __name__ == "__main__":
    main()
